### ISSUE TITLE
Undate

### ISSUE THREAD

**Issue by SvarogZ** [1337joe/du-mocks#1]
Hi!

Are you going to do an update for Athena?
https://du.w3asel.com/du-mocks/mock-codex/modules/ContainerUnit.html

**Comment by 1337joe** [comment]
I started and I will get to it, but I've had a lot going on lately and barely have had time to log in. Hopefully I can make some progress this weekend.

**Comment by 1337joe** [comment]
Did a first pass at updating for Athena and pushed it to my hosting a couple weeks ago but had forgotten to push to github. Just did that, let me know if you run across anything I missed/got wrong.
